name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]


jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Playwright tests
        run: npm run test:e2e
      - name: Notify build failure
        if: failure()
        uses: rjstone/discord-webhook-notify@v2.2.1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          title: "Build failed"
          description: |
            commit ${{ github.event.head_commit.url }} by ${{ github.actor }} broke the build :(
          details: |
            Repo: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Message: ${{ github.event.head_commit.message }}
            Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

  deploy:
    needs: simple_deployment_pipeline
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.API_RENDER_KEY }}
      - name: Notify deployment success
        if: success()
        uses: rjstone/discord-webhook-notify@v2.2.1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          title: "A new version Pokedex deployed"
          description: |
            to ${{ vars.RENDER_URL }} by ${{ github.actor }}
          footer: "Severity: informational"


  tag_release:
    needs: deploy
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
